### ISSUE TITLE
`stringToTerm`: Literals with datatype in brackets include brackets in `namedNode` of datatype

### ISSUE THREAD

**Issue by jeswr** [rubensworks/rdf-string.js#38]

**Comment by rubensworks** [comment]
For reference to other, could you give an example of the issue in the description?

**Comment by jeswr** [comment]
If I run `stringFromTerm("'o'^^<http://example.org/string>")` then it gets parsed to a literal where the `namedNode` representing the datatype has value `<http://example.org/string>` even though the value of that namedNode should be `http://example.org/string`

**Comment by rubensworks** [comment]
That's actually intentional, see the examples in https://github.com/rubensworks/rdf-string.js#rdf-string

(This lib uses the same internal representation as N3.js, and is therefore not exactly the same as how things are represented in Turtle) (Also see https://github.com/rubensworks/rdf-string-ttl.js)

**Comment by jeswr** [comment]
Ah, I made #39 before reading this comment.

Does it still make sense to enable this within quoted triples like https://github.com/rubensworks/rdf-string.js/blob/9081fc4032429888b287e0849c418a575476280f/test/TermUtil-test.ts#L381-L396? If https://github.com/rdfjs/N3.js/pull/311 is accepted then the internal representation is going to be different between here and N3.js anyway because of [this change](https://github.com/rdfjs/N3.js/blob/56cc184f78761db27751aa4a8489239e0c287666/src/N3DataFactory.js#L250-L261) to support deeply nested quotes which previously could not be parsed by N3.js

**Comment by rubensworks** [comment]
> Does it still make sense to enable this within quoted triples?

Would this be required for nested triples?
If not, I would drop the datatype brackets both within and without nested triples, just so it's consistent everywhere.
Unless there is a particular reason why this would be needed here?

> If https://github.com/rdfjs/N3.js/pull/311 is accepted then the internal representation is going to be different between here and N3.js anyway because of [this change](https://github.com/rdfjs/N3.js/blob/56cc184f78761db27751aa4a8489239e0c287666/src/N3DataFactory.js#L250-L261) to support deeply nested quotes which previously could not be parsed by N3.js

I think the difference is fine.

This library here was originally created to help transition between the old N3.js format and the new RDF/JS terms. But now, this lib has become more of a term serialization library. So it's ok if we don't remain fully aligned with N3.js, as long as we remain backwards-compatible with our initial representation.

**Comment by jeswr** [comment]
> Unless there is a particular reason why this would be needed here?

So long as rdf-string isn't used to parse/serialise quads outside in sparqlee (outside of tests) I don't think it is a problem.

**Comment by rubensworks** [comment]
Ok, so we can leave things as-is then? Ok to close this issue?

**Comment by jeswr** [comment]
Yep :)
